### ISSUE TITLE
Add function "initialize_checks_per_block!(conf)"

### ISSUE THREAD

**Issue by lydiakienbaum** [janattig/SudokuPlantDesign.jl#1]
Function enables to distribute randomly all checks per check types per block - to visualize the distribution of checks of a standard augmented design without optimization.

**Comment by janattig** [comment]
Function `initialize_checks_per_block!` is already implemented, see [here](https://github.com/janattig/SudokuPlantDesign.jl/blob/16a4a021ec3afab0f2606295b7dcf158aa9f19d3/src/check_configuration/utility_functions.jl#L81), also tested working.

Try executing the following to try it out:
```julia
conf = get_configuration([9,9],[2,2,2,2],3)
initialize_checks_per_block!(conf)  
show_configuration(conf)    
```

**Comment by lydiakienbaum** [comment]
thanks, that solves the issue!

**Comment by janattig** [comment]
great!
